version: '2'
services:
  dnsmasq:
    restart: always
    image: andyshinn/dnsmasq
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      # Port already in use と言われたときは、
      # https://www.linuxuprising.com/2020/07/ubuntu-how-to-free-up-port-53-used-by.html をもとに
      # UbuntuのデフォルトのDNSサーバーを落とす
    extra_hosts:
      - "local.example.com:127.20.0.1"
      - "local.aa.com:192.168.43.240"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
