# example
version: '3'
services:
  lcov-report:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: /bin/bash -c "while true; do sleep 24h && /bin/bash /scripts/my_script.sh; done"
    environment:
      repo: "YOUR_REPO"
    ports: 
     - "8000:80"
    volumes:
      - "./ssh:/root/.ssh:ro"
    command: bash /app/report.sh

