version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: vm-gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      gitea_network:
        ipv4_address: 10.254.249.89
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  drone:
    container_name: vm-gitea-drone
    image: drone/drone:latest
    restart: unless-stopped
    depends_on:
      - gitea
    networks:
      gitea_network:
        ipv4_address: 10.254.249.87
    environment:
      # https://docs.drone.io/server/provider/gitea/
      - TZ=Japan
      - DRONE_GIT_ALWAYS_AUTH=false
      # 必要な文字列値は、外部ホスト名またはIPアドレス
      - DRONE_SERVER_HOST=10.254.249.87:8090
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RPC_SECRET=123456789_test_secret_gitea_holsdfoifeuawrldkv
      # 必要な文字列値は、Giteaサーバアドレス
      - DRONE_GITEA_SERVER=http://10.254.249.89:3000
      # 必要な文字列値は、Gitea oauthクライアントID
      - DRONE_GITEA_CLIENT_ID=2f31ae12-773d-44e2-ae27-50f68dc0759d
      # 必要な文字列値は、Gitea oauthクライアントシークレット
      - DRONE_GITEA_CLIENT_SECRET=gto_hd67dwgfm2kmns6yu5nauvoopgjhytcghlbyfqdmcij7jggurvpq
      - DRONE_USER_CREATE="username:sample,admin:true"
      - DRONE_GITEA_SKIP_VERIFY=true
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_GITEA_ALWAYS_AUTH=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone:/data
    ports:
      - "8090:80"
      - "443:443"

  drone-runner:
    container_name: vm-gitea-drone-runner
    image: drone/drone-runner-docker:latest
    restart: unless-stopped
    depends_on:
      - drone
    environment:
      # https://docs.drone.io/runner/docker/installation/linux/
      # https://docs.drone.io/server/metrics/
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=10.254.249.87:8090
      - DRONE_RPC_SECRET=123456789_test_secret_gitea_holsdfoifeuawrldkv
      - DRONE_RUNNER_NAME="gitea-drone-runner"
      # ランナーが実行できる同時パイプラインの数
      - DRONE_RUNNER_CAPACITY=2
      # - DRONE_DEBUG=false
      # - DRONE_RUNNER_ENV_FILE="/etc/drone.env"
      - DRONE_TRACE=true
      - DRONE_RPC_DUMP_HTTP=true
      - DRONE_RPC_DUMP_HTTP_BODY=true
    ports:
      - "3002:3000"
    networks:
      gitea_network:
        ipv4_address: 10.254.249.86
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:14
    restart: always
    container_name: vm-gitea-postgres
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea_network
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  gitea_network:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 10.254.249.0/24
