version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "8000:80"
    environment:
      AUTH_TYPE: Basic 
      USERNAME: hoge
      PASSWORD: fuga
      LOCATION: /
    volumes:
      - ./data:/var/lib/dav

