version: "3.7"
services:
    app:
      image: node:14.0.0
      container_name : node_docker_app
      working_dir: /app
      tty: true
      volumes:
        - ./:/app
      command:
        bash -c "npm install && 
        npm start"
      ports:
        - "3000:3000"
      # 環境変数の設定
      environment:
        - DEBUG=app:* 
