version: '3'
services:
  mongo:
    image: mongo:focal
    container_name : mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo 
      MONGO_INITDB_ROOT_PASSWORD: mongoPass
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
  mongo-express:
    image: mongo-express:latest
    container_name : mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo 
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoPass 
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo


